spring:
  profiles:
    active:
    - dev
---
server:
  port: 6699
spring:
  application:
     name: plat-server
  profiles: dev
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/ #告诉服务提供者要把服务注册到哪儿，控制中心的网址
  instance:
    prefer-ip-address: true #显示客户端真实ip
---
server:
  port: 9966
spring:
  application:
     name: plat-server
  profiles: test
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/ #告诉服务提供者要把服务注册到哪儿，控制中心的网址
  instance:
    prefer-ip-address: true #显示客户端真实ip